version: '3'

services:
  database:
    container_name: database
    image: mysql:latest
    ports:
      - 3306:3306
    env_file:
      - .secrets
    # environment:
    #   - $MYSQL_ROOT_PASSWORD:MYSQL_ROOT_PASSWORD
    #   - MYSQL_DATABASE:$MYSQL_DATABASE
    #   - MYSQL_USER:$MYSQL_USER
    #   - MYSQL_PASSWORD:$MYSQL_PASSWORD
    volumes:
      - datavol:/var/lib/mysql
  
  ldap:
    image: rroemhild/test-openldap
    container_name: openldap
    ports:
      - 10389:10389
      - 10636:10636

volumes:
  datavol: